version: '3.8'
services:
  portainer:
    image: portainer/portainer-ce
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - monitor-net

  uptime-kuma:
    image: louislam/uptime-kuma
    ports:
      - "3001:3001"
    networks:
      - monitor-net

  redis:
    image: redis:alpine
    networks:
      - monitor-net

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - monitor-net

networks:
  monitor-net:
    driver: bridge